name: 'GitHub Actions Backend'
inputs:
  run_number:
    required: true
  github_token:
    required: true
  github_user:
    required: true
  octopus_server_url:
    required: true
  octopus_api_token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.3.0'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - name: Install modules
      run: ./mvnw --batch-mode install
      shell: bash
      working-directory: java/products-service

    - name: Update version
      run: ./mvnw --batch-mode build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}.${{ github.run_number }}
      shell: bash
      working-directory: java/products-service

    - name: List dependencies
      run: mvn --batch-mode dependency:tree --no-transfer-progress
      shell: bash
      working-directory: java/products-service

    - name: Build with Maven
      run: ./mvnw --batch-mode package --file pom.xml -Pnative -DskipTests -Dquarkus.profile=prod
      shell: bash
      working-directory: java/products-service

#    - name: Test Backend
#      run: mvn --batch-mode test
#      shell: bash
#      working-directory: java/products-service

    - name: Rename zip
      run: >
        mv target/function.zip
        products-service.0.0.1.${{ inputs.run_number }}.zip
      shell: bash
      working-directory: java/products-service

    - run: >
        ./mvnw deploy:deploy-file
        -Dfile=products-service.0.0.1.${{ inputs.run_number }}.zip
        -DgroupId=com.octopus.octopub
        -DartifactId=products-service
        -Dversion=0.0.1.${{ github.run_number }}
        -Dpackaging=zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/mcasperson/OctoPub"
      shell: bash
      working-directory: java/products-service

    - name: Generate SBOM
      run: mvn cyclonedx:makeAggregateBom -DskipTests
      shell: bash
      working-directory: java/products-service

    - name: Build SBOM package
      run: >
        octo pack
        --id products-service-sbom
        --version 0.0.1.${{ inputs.run_number }}
        --format zip
        --include **/bom.xml
      shell: bash
      working-directory: java/products-service

    - run: >
        ./mvnw deploy:deploy-file
        -Dfile=products-service-sbom.0.0.1.${{ inputs.run_number }}.zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/mcasperson/OctoPub"
        -DgroupId=com.octopus.octopub
        -DartifactId=products-service-sbom
        -Dversion=0.0.1.${{ github.run_number }}
        -Dpackaging=zip
      shell: bash
      working-directory: java/products-service

    - name: Trigger deployment
      run: >
        octo create-release
        --project "Products Service"
        --deployTo "Development"
        --waitForDeployment
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Octopub"
      shell: bash