name: 'GitHub Actions Backend'
inputs:
  run_number:
    required: true
  github_token:
    required: true
  github_user:
    required: true
  dockerhub_username:
    required: true
  dockerhub_password:
    required: true
  octopus_server_url:
    required: true
  octopus_api_token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.3.0'
        java: 'java17'
        arch: 'amd64'

    - name: Install native-image component
      run: gu install native-image
      shell: bash

    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.4.0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - name: Checkstyle
      run: ./mvnw --batch-mode checkstyle:check
      shell: bash
      working-directory: java/products-service

    # Update the deployment.yaml file to trigger a GitOps deployment
    - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'java/products-service/k8s/deployment.yaml'
        propertyPath: 'spec.template.spec.containers.0.image'
        value: "octopussamples/octopub-products:0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}"
        message: "Updated image reference"
        createPR: false

    - name: Install modules
      run: ./mvnw --batch-mode install
      shell: bash
      working-directory: java/products-service

    - name: Update version
      run: ./mvnw --batch-mode build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.${{ github.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
      shell: bash
      working-directory: java/products-service

    - name: List Dependencies
      run: ./mvnw --batch-mode dependency:tree --no-transfer-progress > dependencies.txt
      shell: bash
      working-directory: java/products-service

    - name: Collect Dependencies
      uses: actions/upload-artifact@v2
      with:
        name: Dependencies
        path: java/products-service/dependencies.txt

    - name: List Dependency Updates
      run: ./mvnw --batch-mode versions:display-dependency-updates > dependencyUpdates.txt
      shell: bash
      working-directory: java/products-service

    - name: Collect Dependency Updates
      uses: actions/upload-artifact@v2
      with:
        name: Dependencies Updates
        path: java/products-service/dependencyUpdates.txt

    - name: Build with Maven
      run: ./mvnw --batch-mode package --file pom.xml -Pnative -DskipTests -Dquarkus.profile=prod
      shell: bash
      working-directory: java/products-service

    - name: Rename zip
      run: >
        mv target/function.zip
        products-service.0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}.zip
      shell: bash
      working-directory: java/products-service

    - run: >
        ./mvnw deploy:deploy-file
        -Dfile=products-service.0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}.zip
        -DgroupId=com.octopus.octopub
        -DartifactId=products-service
        -Dversion=0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
        -Dpackaging=zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/${{ github.repository }}"
      shell: bash
      working-directory: java/products-service

    - name: Generate SBOM
      run: mvn cyclonedx:makeAggregateBom -DskipTests
      shell: bash
      working-directory: java/products-service

    - name: Build SBOM package
      run: >
        octo pack
        --id products-service-sbom
        --version 0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
        --format zip
        --include **/bom.xml
      shell: bash
      working-directory: java/products-service

    - run: >
        ./mvnw deploy:deploy-file
        -Dfile=products-service-sbom.0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}.zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/${{ github.repository }}"
        -DgroupId=com.octopus.octopub
        -DartifactId=products-service-sbom
        -Dversion=0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
        -Dpackaging=zip
      shell: bash
      working-directory: java/products-service

    - run: |
        pack build --builder heroku/buildpacks:20 --env "MAVEN_CUSTOM_GOALS=clean package -Dquarkus.profile=dist" octopussamples/octopub-products
        docker push octopussamples/octopub-products
        docker tag octopussamples/octopub-products:latest octopussamples/octopub-products:0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
        docker push octopussamples/octopub-products:0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
      shell: bash
      working-directory: java/products-service

    - name: Generate Octopus Deploy build information
      uses: xo-energy/action-octopus-build-information@v1.1.2
      with:
        octopus_api_key: ${{ inputs.octopus_api_token }}
        octopus_project: Products Service
        octopus_server: ${{ inputs.octopus_server_url }}
        push_version: 0.1.${{ inputs.run_number }}${{ env.BRANCH_NAME != 'master' && format('-{0}', env.BRANCH_NAME) || ''  }}
        push_package_ids: com.octopus.octopub:products-service
        push_overwrite_mode: OverwriteExisting
        output_path: octopus
        octopus_space: "Octopub"
        octopus_environment: "Development"

    - name: Trigger deployment
      if: ${{ env.BRANCH_NAME == 'master' }}
      run: >
        octo create-release
        --project "Products Service"
        --deployTo "Development"
        --waitForDeployment
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Octopub"
        --gitRef master
      shell: bash

    - name: Trigger deployment to security
      if: ${{ env.BRANCH_NAME == 'master' }}
      run: >
        octo deploy-release
        --project "Products Service"
        --deployTo "Development (Security)"
        --waitForDeployment
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Octopub"
        --version=latest
      shell: bash

    - name: Trigger branch deployment
      if: ${{ env.BRANCH_NAME != 'master' }}
      run: >
        octo create-release
        --project "Product Service Branch"
        --deployTo "Development"
        --waitForDeployment
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Octopub"
        --gitRef master
      shell: bash