version: "3.9"
services:
  frontend:
    image: "octopussamples/octopub-frontend"
    pull_policy: always
    ports:
      - "7080:7080"
  products:
    image: "octopussamples/octopub-products"
    pull_policy: always
    ports:
      - "8083:8083"
    environment:
      AUDIT_SERVICE: "http://localhost:9080"
  audits:
    image: "octopussamples/octopub-audits"
    pull_policy: always
    ports:
      - "9080:9080"
