apiVersion: apps/v1
kind: Deployment
metadata:
  name: audits-service
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: audits-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: audits-service
    spec:
      containers:
        - name: randomquotes
          image: octopussamples/octopub-audits:latest octopussamples/octopub-audits:0.1.214
          ports:
            - name: web
              containerPort: 8083
