name: 'Pipeline Frontend'
inputs:
  run_number:
    required: true
  github_token:
    required: true
  github_user:
    required: true
  octopus_server_url:
    required: true
  octopus_api_token:
    required: true
on:
  push:
  workflow_dispatch:

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v1

    - uses: nelonoel/branch-name@v1.0.1

    - name: Install Octopus Deploy CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.3124

    - name: Packages
      run: yarn install
      shell: bash
      working-directory: js

    - name: Build
      run: yarn build
      shell: bash
      working-directory: js

    - name: Copy config file
      run: cp config.json build
      shell: bash
      working-directory: js

    - name: Install CycloneDX
      run: npm install -g @cyclonedx/bom
      shell: bash
      working-directory: js

    - name: Generate SBOM
      run: cyclonedx-bom
      shell: bash
      working-directory: js

    - name: Create zip
      run: cd build; zip -r ../octopub-frontend.0.1.0.${{ inputs.run_number }}.zip .
      shell: bash
      working-directory: js

    - name: Create zip
      run: zip octopub-frontend-sbom.0.1.0.${{ inputs.run_number }}.zip bom.xml
      shell: bash
      working-directory: js

    - run: >
        mvn deploy:deploy-file
        -Dfile=octopub-frontend.0.1.0.${{ inputs.run_number }}.zip
        -DgroupId=com.octopus.octopub
        -DartifactId=octopub-frontend
        -Dversion=0.0.1.${{ github.run_number }}
        -Dpackaging=zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/${{ github.repository }}"
      shell: bash
      working-directory: js

    - run: >
        mvn deploy:deploy-file
        -Dfile=octopub-frontend-sbom.0.1.0.${{ inputs.run_number }}.zip
        -DgroupId=com.octopus.octopub
        -DartifactId=octopub-frontend-sbom
        -Dversion=0.0.1.${{ github.run_number }}
        -Dpackaging=zip
        -Durl="https://${{ inputs.github_user }}:${{ inputs.github_token }}@maven.pkg.github.com/${{ github.repository }}"
      shell: bash
      working-directory: js

    - name: Trigger deployment Frontend
      run: >
        octo create-release
        --project "Octopub Frontend"
        --deployTo "Development"
        --waitForDeployment
        --server ${{ inputs.octopus_server_url }}
        --apiKey ${{ inputs.octopus_api_token }}
        --space "Octopub"
      shell: bash