apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: randomquotes
          image: octopussamples/octopub-frontend:0.1.131
          volumeMounts:
          - name: config-volume
            mountPath: /workspace/config.json
            subPath: config.json
          ports:
            - name: web
              containerPort: 7080
  volumes:
    - name: config-volume
      configMap:
        name: webconfig