apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(static/(css|js)/)?[a-zA-Z0-9-.]+?\.(json|html|css|js|png|jpg|jpeg|gif|map|txt)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80