apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: octopussamples/octopub-products:0.1.252
          ports:
            - name: web
              containerPort: 8083
          env:
            - name: MIGRATE_AT_START
              value: !str "true"
