apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-service
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
          - path: /health/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80