name: Hello World

on:
  push:
      paths:
      - 'go/hello-world/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ./go/hello-world/build
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_user: ${{ github.actor }}