name: Products Service

on:
  push:
      paths:
      - 'java/products-service/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ./java/products-service/github
      with:
        run_number: ${{ github.run_number }}
        github_token: ${{ github.actor }}
        github_user: ${{ secrets.GITHUB_TOKEN }}