name: Products Service

on:
  push:
      paths:
      - 'java/products-service/**'
      - '!java/products-service/k8s/**'
  workflow_dispatch:

jobs:
  build:
    # We can't run on ubuntu-latest, as that has updated GLIBC to a version that
    # is incompatible with Lambdas.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ./java/products-service/github
      with:
        run_number: ${{ github.run_number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_user: ${{ github.actor }}
        dockerhub_username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
        dockerhub_password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
        octopus_server_url: ${{ secrets.OCTOPUS_URL }}
        octopus_api_token: ${{ secrets.OCTOPUS_API_KEY }}