name: Votes Service

on:
  push:
      paths:
      - 'go/votes-service/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: ./go/votes-service/build
      with:
        directory: ./go/votes-service
        main: ./cmd/web/main.go
        token: ${{ secrets.GITHUB_TOKEN }}